# -*- coding: utf-8 -*-
"""mmkcr_fakeddit_PHASE3_appended.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5YZmNj5qwGvSBGkl1Rrva-8h-qBWYzF

# MMCR × Fakeddit: Multimodal Conflict Detection (10000-sample demo)

This notebook builds a small, **reproducible pipeline** to detect **image–text conflicts** using your available Fakeddit TSVs:
- `/mnt/data/multimodal_train.tsv`
- `/mnt/data/multimodal_validate.tsv`
- `/mnt/data/multimodal_test_public.tsv`

**What it does**  
1) Load data and sample ~200 items with valid `image_url`, `title`, and `6_way_label`.  
2) Download images locally.  
3) Generate **image captions** using **BLIP**.  
4) Compute **CLIP** similarity between title ↔ image.  
5) Run **NLI (roberta-large-mnli)** on `title` vs **caption** → `supports / contradicts / unrelated`.  
6) Fuse signals into a **conflict label** and **score**.  
7) Map Fakeddit 6-way ground truth to conflict targets and evaluate with **metrics & plots**.  
8) Save a complete `results.csv` and visualizations to `./mmcr_outputs`.

> **Tip:** Use a GPU runtime in Google Colab for speed. Internet access is required to download models and images.
"""

!pip install -q bitsandbytes accelerate

# ===========================================================
# 🔗 Mount Google Drive (save all outputs persistently)
# ===========================================================
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define your project folder inside Drive
BASE_DIR = "/content/drive/MyDrive/MMCR_Fakeddit_Experiment"
!mkdir -p "$BASE_DIR"

print("Drive mounted successfully. Outputs will be saved in:", BASE_DIR)

!pip -q install transformers accelerate timm pillow torch torchvision torchaudio --upgrade
!pip -q install scikit-learn matplotlib pandas tqdm requests

!pip install rouge-score nltk transformers torch torchvision pillow scikit-learn tqdm --quiet

!pip install bert-score --quiet

# ---- Compatibility setup: PIL/Pillow fix ----
!pip uninstall -y pillow pillow-simd >/dev/null 2>&1
!pip install -q --no-cache-dir pillow==10.3.0

# (Re)install core deps
!pip install -q --upgrade transformers accelerate timm pandas scikit-learn matplotlib tqdm requests

import PIL, sys
print("Pillow version:", PIL.__version__)
print("Python:", sys.version)

# ==== Load using your exact columns (clean_title, image_url, 6_way_label) ====
import os, pandas as pd, numpy as np

TRAIN_TSV = "/mnt/data/multimodal_train.tsv"
VALID_TSV = "/mnt/data/multimodal_validate.tsv"
TEST_TSV  = "/mnt/data/multimodal_test_public.tsv"

# Canonical column names for the rest of the notebook
TEXT_COL  = "clean_title"
IMAGE_COL = "image_url"
LABEL_COL = "6_way_label"

# How many samples you want
N_SAMPLES = 10000
SEED = 42

def _load(fp):
    if not fp or not os.path.exists(fp):
        print(f"Missing: {fp}")
        return None
    try:
        return pd.read_csv(fp, sep="\t")
    except Exception as e:
        print(f"Read error for {fp}: {e}")
        return None

dfs = []
for fp in [TRAIN_TSV, VALID_TSV, TEST_TSV]:
    df = _load(fp)
    if df is None:
        continue
    # Only keep columns we need if present
    keep = [c for c in [TEXT_COL, IMAGE_COL, LABEL_COL, "hasImage"] if c in df.columns]
    if len(keep) < 2:
        print(f"⚠️ Insufficient columns in {fp}. Found: {df.columns.tolist()[:10]}")
        continue
    sub = df[keep].copy()
    # Optional: keep only rows with hasImage == True if column exists
    if "hasImage" in sub.columns:
        sub = sub[sub["hasImage"] == True]
    dfs.append(sub)

if not dfs:
    raise FileNotFoundError("No TSVs could be loaded with the expected columns.")

data = pd.concat(dfs, ignore_index=True)

# Basic cleaning
data[TEXT_COL]  = data[TEXT_COL].astype(str).str.strip()
data[IMAGE_COL] = data[IMAGE_COL].astype(str).str.strip()

# Keep http/https links (comment out if you have local paths)
data = data[data[IMAGE_COL].str.startswith(("http://","https://"))]

# Labels: keep as strings for consistency downstream
if LABEL_COL in data.columns:
    data[LABEL_COL] = data[LABEL_COL].astype(str).str.strip()

print("Rows after cleaning:", len(data))
if LABEL_COL in data.columns:
    print("Label distribution (first 10):")
    print(data[LABEL_COL].value_counts().head(10))

# Build sampling pool: prefer labeled rows from train/valid; otherwise any rows available
pool = data.dropna(subset=[TEXT_COL, IMAGE_COL]).copy()
if LABEL_COL in pool.columns:
    # Keep rows where label is one of the observed numeric codes (as strings)
    observed = sorted(pool[LABEL_COL].dropna().unique().tolist())
    pool = pool[pool[LABEL_COL].isin(observed)]

# Final sample
take = min(N_SAMPLES, len(pool))
if take == 0:
    raise ValueError("No usable rows after filtering. Check column names and URL filtering.")
if take < N_SAMPLES:
    print(f"Requested {N_SAMPLES}, only {take} available. Sampling {take}.")

data_sample = pool.sample(n=take, random_state=SEED).reset_index(drop=True)
print("Sampled rows:", len(data_sample))
data_sample.head(50)

# ==== Directly use multimodal_train.tsv (robust + Drive paths) ====
import os, re, urllib.parse, hashlib
from io import BytesIO
from pathlib import Path
import pandas as pd, numpy as np
from PIL import Image
import requests
from requests.adapters import HTTPAdapter, Retry
from tqdm import tqdm
from google.colab import drive

# --- Mount Drive ---
drive.mount('/content/drive', force_remount=True)
DRIVE_IMG_DIR = Path("/content/drive/MyDrive/MMCR_Fakeddit_Images")
DRIVE_IMG_DIR.mkdir(parents=True, exist_ok=True)

# --- File path & config ---
TRAIN_TSV = "/mnt/data/multimodal_train.tsv"
TEXT_COL, IMAGE_COL, LABEL_COL, HAS_IMAGE = "clean_title", "image_url", "6_way_label", "hasImage"
N_SAMPLES, SEED = 10000, 42

# --- Load dataset (only needed columns) ---
df = pd.read_csv(TRAIN_TSV, sep="\t", usecols=[TEXT_COL, IMAGE_COL, LABEL_COL, HAS_IMAGE])

# 1) Keep rows that claim to have images
if HAS_IMAGE in df.columns:
    df = df[df[HAS_IMAGE] == True]

# 2) Drop rows with missing/empty text or URLs
df = df.dropna(subset=[TEXT_COL, IMAGE_COL]).copy()
df = df[df[TEXT_COL].str.strip() != ""]
df = df[df[IMAGE_COL].str.strip() != ""]

# 3) Keep only http/https image links
df = df[df[IMAGE_COL].str.startswith(("http://", "https://"), na=False)].reset_index(drop=True)
print("Rows with valid http(s) URLs:", len(df))

# --- Helper: rewrite preview URLs to direct images ---
IMG_EXT_RE = re.compile(r"\.(jpg|jpeg|png|webp|bmp)$", re.I)

def rewrite_image_url(url: str) -> str:
    url = url.strip()
    if not url.startswith(("http://","https://")): return ""
    try:
        p = urllib.parse.urlparse(url)
        host = (p.netloc or "").lower()
        q = urllib.parse.parse_qs(p.query or "")

        # Embedded ?url=<real image>
        if "url" in q and q["url"]:
            cand = urllib.parse.unquote(q["url"][0])
            if cand.startswith(("http://","https://")):
                return cand

        # Reddit preview → i.redd.it
        if any(h in host for h in ["external-preview.redd.it","preview.redd.it","previews.redd.it"]):
            path = p.path or ""
            if not IMG_EXT_RE.search(path): path += ".jpg"
            return f"https://i.redd.it{path}"

        # i.redd.it → strip query
        if "i.redd.it" in host:
            return urllib.parse.urlunparse(("https","i.redd.it",p.path or "","","",""))

        # imgur.com page → i.imgur.com file (ensure extension)
        if host in ["imgur.com","www.imgur.com"]:
            base = (p.path or "").strip("/")
            if not base: return url
            if not IMG_EXT_RE.search(base): base += ".jpg"
            return f"https://i.imgur.com/{base}"

        # i.imgur.com → ensure extension
        if host == "i.imgur.com":
            path = p.path or ""
            if not IMG_EXT_RE.search(path): path += ".jpg"
            return urllib.parse.urlunparse(("https","i.imgur.com",path,"","",""))

        return url
    except Exception:
        return url

df["fetch_url"] = df[IMAGE_COL].astype(str).apply(rewrite_image_url)
df = df[df["fetch_url"].str.startswith(("http://","https://"), na=False)].reset_index(drop=True)
print("After URL rewrite:", len(df), "rows")

# --- Sample up to N_SAMPLES (try to keep label balance if labels exist) ---
if len(df) > N_SAMPLES and LABEL_COL in df.columns:
    # proportional per-label sample, with at least 1 per present class
    per_label = (
        df.groupby(LABEL_COL, group_keys=False)
          .apply(lambda g: g.sample(n=max(1, int(round(N_SAMPLES * len(g) / len(df)))), random_state=SEED))
    ).reset_index(drop=True)
    # Trim if rounding overshot
    if len(per_label) > N_SAMPLES:
        df = per_label.sample(n=N_SAMPLES, random_state=SEED).reset_index(drop=True)
    else:
        df = per_label
else:
    df = df.sample(n=min(N_SAMPLES, len(df)), random_state=SEED).reset_index(drop=True)

print("Sampled rows:", len(df))

# --- HTTP session (retries, headers) ---
def build_session():
    s = requests.Session()
    retries = Retry(total=3, backoff_factor=0.4,
                    status_forcelist=[429,500,502,503,504],
                    allowed_methods=["GET","HEAD"])
    s.mount("http://", HTTPAdapter(max_retries=retries))
    s.mount("https://", HTTPAdapter(max_retries=retries))
    s.headers.update({
        "User-Agent": "Mozilla/5.0",
        "Accept": "image/avif,image/webp,image/*,*/*;q=0.8",
    })
    return s

SESSION = build_session()

def fetch_image(url: str, timeout=10):
    try:
        r = SESSION.get(url, timeout=timeout, stream=True)
        r.raise_for_status()
        if "image/" not in r.headers.get("Content-Type","").lower():
            return None
        return Image.open(BytesIO(r.content))
    except Exception:
        return None

def save_image(img: Image.Image, path: Path) -> str | None:
    ext = path.suffix.lower()
    fmt = {".jpg":"JPEG",".jpeg":"JPEG",".png":"PNG",".webp":"WEBP"}.get(ext, "JPEG")
    if fmt in ("JPEG","WEBP") and img.mode not in ("RGB","L"):
        img = img.convert("RGB")
    try:
        img.save(path, format=fmt, quality=90)
        return str(path)
    except Exception:
        fb = path.with_suffix(".jpg")
        try:
            img.convert("RGB").save(fb, format="JPEG")
            return str(fb)
        except Exception:
            return None

# --- Download to Drive and add drive_path ---
drive_paths, ok_mask = [], []
for i, row in tqdm(df.iterrows(), total=len(df)):
    url = row["fetch_url"]
    img = fetch_image(url)
    if img is None:
        drive_paths.append("")
        ok_mask.append(False)
        continue
    m = IMG_EXT_RE.search(url)
    ext = "." + m.group(1).lower() if m else ".jpg"
    h = hashlib.md5(url.encode("utf-8")).hexdigest()[:8]
    fn = f"{i:04d}_{h}{ext}"
    path = DRIVE_IMG_DIR / fn
    saved = save_image(img, path)
    drive_paths.append(saved if saved else "")
    ok_mask.append(bool(saved))

df["drive_path"] = drive_paths
df = df[np.array(ok_mask)].reset_index(drop=True)

# --- Save updated dataset ---
csv_out = DRIVE_IMG_DIR / "train_sample_with_drive_paths.csv"
df.to_csv(csv_out, index=False)
print(f"✅ Downloaded {len(df)} images to Drive.")
print(f"📄 CSV saved at: {csv_out}")

df.head(50)

import pandas as pd

csv_out = "/content/drive/MyDrive/MMCR_Fakeddit_Images/train_sample_with_drive_paths.csv"
df = pd.read_csv(csv_out)
print("Loaded rows:", len(df))
df.head()

# ==== IMAGE CAPTIONING & TEXT COMPARISON PIPELINE (conflict-aware) ====
import os, math, torch, numpy as np, pandas as pd
from PIL import Image
from tqdm import tqdm
from transformers import (
    BlipProcessor, BlipForConditionalGeneration,
    BertTokenizer, BertModel,
    CLIPProcessor, CLIPModel,
)
from sklearn.metrics.pairwise import cosine_similarity
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

# Ensure nltk is installed and BLEU works
import nltk
nltk.download('punkt', quiet=True)

# ==========================================
# 1) BLIP: image → caption  (title-like text)
# ==========================================
import torch
from tqdm import tqdm
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

# ---- Device setup ----
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# ---- Load BLIP ----
blip_name = "Salesforce/blip-image-captioning-base"
blip_proc  = BlipProcessor.from_pretrained(blip_name)
blip_model = BlipForConditionalGeneration.from_pretrained(blip_name).to(device)
blip_model.eval()

@torch.no_grad()
def generate_caption(img_path):
    """Generate caption for one image using BLIP."""
    try:
        img = Image.open(img_path).convert("RGB")
        inputs = blip_proc(images=img, return_tensors="pt").to(device)
        out = blip_model.generate(**inputs, max_new_tokens=40)
        return blip_proc.decode(out[0], skip_special_tokens=True)
    except Exception as e:
        print(f"[WARN] Could not caption {img_path}: {e}")
        return ""

# ---- Generate only if needed ----
if "blip_caption" not in df.columns or df["blip_caption"].isna().any():
    df["blip_caption"] = [generate_caption(p) for p in tqdm(df["drive_path"], desc="Captioning images")]
else:
    print("✅ BLIP captions already present, skipping generation.")

# ===================================================
# 2) Text similarity: title vs BLIP caption (3 metrics)
# ===================================================
bert_tok   = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased").to(device)
bert_model.eval()

@torch.no_grad()
def bert_embed(text):
    toks = bert_tok(text, return_tensors="pt", truncation=True, padding=True, max_length=64).to(device)
    out  = bert_model(**toks)
    emb  = out.last_hidden_state.mean(dim=1).cpu().numpy()
    return emb

smooth = SmoothingFunction().method1
rouge  = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

bleu_scores, rouge_scores, cosine_scores = [], [], []

for title, caption in tqdm(zip(df["clean_title"], df["blip_caption"]), total=len(df), desc="Text similarity"):
    if not caption or not title:
        bleu_scores.append(0.0); rouge_scores.append(0.0); cosine_scores.append(0.0)
        continue

    # BLEU
    bleu = sentence_bleu([title.split()], caption.split(), smoothing_function=smooth)
    bleu_scores.append(float(bleu))

    # ROUGE-L
    rougeL = rouge.score(title, caption)["rougeL"].fmeasure
    rouge_scores.append(float(rougeL))

    # BERT cosine
    e1, e2 = bert_embed(title), bert_embed(caption)
    cos = float(cosine_similarity(e1, e2)[0][0])
    cosine_scores.append(cos)

df["bleu"]        = bleu_scores
df["rougeL"]      = rouge_scores
df["bert_cosine"] = cosine_scores

print("Computed BLEU, ROUGE-L, BERT-cosine")
print(df[["clean_title", "blip_caption", "bleu", "rougeL", "bert_cosine"]].head(5))

# ===================================================
# 3) CLIP side: image ↔ title, image ↔ caption
#     (so we can know if the caption is actually closer)
# ===================================================
clip_name = "openai/clip-vit-large-patch14"
clip_proc  = CLIPProcessor.from_pretrained(clip_name)
clip_model = CLIPModel.from_pretrained(clip_name).to(device).eval()

@torch.no_grad()
def clip_sim(text: str, img_path: str):
    try:
        img = Image.open(img_path).convert("RGB")
        batch = clip_proc(text=[str(text)], images=[img], return_tensors="pt", padding=True).to(device)
        out   = clip_model(**batch)
        return out.logits_per_image.squeeze().item()
    except Exception:
        return np.nan

clip_title_sims   = []
clip_caption_sims = []

for title, caption, pth in tqdm(zip(df["clean_title"], df["blip_caption"], df["drive_path"]),
                                total=len(df), desc="CLIP sims"):
    s_title   = clip_sim(title, pth)
    s_caption = clip_sim(caption if isinstance(caption, str) and caption.strip() else "", pth)
    clip_title_sims.append(s_title)
    clip_caption_sims.append(s_caption)

df["clip_title_image"]   = clip_title_sims
df["clip_caption_image"] = clip_caption_sims
df["delta_clip"]         = df["clip_title_image"] - df["clip_caption_image"]

# ===================================================
# 4) Conflict-y label from text + CLIP (tightened, vectorized, safe)
#     Produces: caption_label ∈ {supports, unrelated, contradicts}
#     Also writes: caption_confidence, caption_probs = [p_sup, p_unrel, p_contra]
#     Optional: if vllm_label/vllm_probs exist, will blend in confident VLLM decisions.
# ===================================================

import numpy as np
import pandas as pd

# --- required columns from earlier cells ---
req = ["bert_cosine","bleu","rougeL","clip_title_image"]
for c in req:
    if c not in df.columns:
        raise ValueError(f"Missing `{c}` — run the BLIP/CLIP+text cell first.")

# --- safe pulls ---
bc = pd.to_numeric(df["bert_cosine"], errors="coerce").fillna(0.0).to_numpy()
bl = pd.to_numeric(df["bleu"],        errors="coerce").fillna(0.0).to_numpy()
rl = pd.to_numeric(df["rougeL"],      errors="coerce").fillna(0.0).to_numpy()
ti = pd.to_numeric(df["clip_title_image"],  errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()
ci = pd.to_numeric(df.get("clip_caption_image", pd.Series(np.nan, index=df.index)),
                   errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()
# delta_clip (title - caption). If absent, compute; still may hold NaNs if ci is NaN.
if "delta_clip" in df.columns:
    dc = pd.to_numeric(df["delta_clip"], errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()
else:
    dc = (pd.Series(ti).astype(float) - pd.Series(ci).astype(float)).to_numpy()

# --- helpers ---
def _pct(vec, q, default):
    v = np.array(vec, float)
    v = v[np.isfinite(v)]
    if v.size < 10:
        return float(default)
    return float(np.percentile(v, q))

def _minmax(x, lo, hi):
    """Scalar min-max to [0,1] with safe denom and neutral 0.5 for NaNs."""
    if not np.isfinite(x): return 0.5
    if hi <= lo + 1e-6:   return 0.5
    return float(np.clip((x - lo) / (hi - lo), 0.0, 1.0))

def _softmax3(a,b,c, temp=1.4):
    v = np.array([a,b,c], float) / max(1e-9, float(temp))
    v = np.exp(v - v.max())
    return v / v.sum()

# --- tighten text thresholds (reduce “all supports”) ---
BC_SUP = max(0.85, _pct(bc, 85, 0.82))
BC_CON = min(0.50, _pct(bc, 35, 0.45))

BL_SUP = max(0.25, _pct(bl, 80, 0.22))
BL_CON = min(0.06,  _pct(bl, 25, 0.05))

RL_SUP = max(0.30, _pct(rl, 80, 0.28))
RL_CON = min(0.06,  _pct(rl, 25, 0.05))

# --- visual thresholds (title↔image) ---
ti_fin = ti[np.isfinite(ti)]
TI_SUP = _pct(ti_fin, 80, 24.5)       # strong title↔image logit
TI_CON = _pct(ti_fin, 20, 20.0)       # weak title↔image logit

# --- delta bands (title vs caption fit to image) ---
dc_fin = (ti - ci)[np.isfinite(ti) & np.isfinite(ci)]
if dc_fin.size >= 20:
    q25, q75 = np.percentile(dc_fin, [25, 75])
    iqr = max(1e-6, q75 - q25)
    DC_STRONG_CON = -0.75 * iqr       # caption≫title on image ⇒ contra
    DC_STRONG_SUP = +0.25 * iqr       # title≥caption on image helps support
else:
    DC_STRONG_CON, DC_STRONG_SUP = -1.0, 0.5

# --- normalize to support/contra channels ---
bc_sup = np.array([_minmax(x, BC_CON, BC_SUP) for x in bc])
bl_sup = np.array([_minmax(x, BL_CON, BL_SUP) for x in bl])
rl_sup = np.array([_minmax(x, RL_CON, RL_SUP) for x in rl])
ti_sup = np.array([_minmax(x, TI_CON, TI_SUP) for x in ti])
dc_sup = np.array([_minmax(x, 0.0, max(DC_STRONG_SUP, 1e-3)) if np.isfinite(x) else 0.5 for x in (ti - ci)])

bc_con = 1.0 - bc_sup
bl_con = 1.0 - bl_sup
rl_con = 1.0 - rl_sup
ti_con = np.array([_minmax(x, TI_SUP, TI_CON) for x in ti])  # inverse band
dc_con = np.array([_minmax(-x, 0.0, max(-DC_STRONG_CON, 1e-3)) if np.isfinite(x) else 0.5 for x in (ti - ci)])

# --- HARD rules (override) ---
hard_support = (
    (bc >= BC_SUP) &
    (np.isfinite(ti) & (ti >= TI_SUP)) &
    (np.isfinite(dc) & (dc >= DC_STRONG_SUP))
)
hard_contra = (
    ((np.isfinite(ti) & (ti <= TI_CON)) & (bc <= BC_CON)) |
    (np.isfinite(dc) & (dc <= DC_STRONG_CON))
)

# --- soft fusion ---
w_bc, w_bl, w_rl, w_ti, w_dc = 0.40, 0.15, 0.15, 0.20, 0.10
s_score = w_bc*bc_sup + w_bl*bl_sup + w_rl*rl_sup + w_ti*ti_sup + w_dc*dc_sup
c_score = w_bc*bc_con + w_bl*bl_con + w_rl*rl_con + w_ti*ti_con + w_dc*dc_con
u_score = 1.0 - np.minimum(1.0, np.abs(s_score - c_score) + 0.35*(s_score + c_score))

probs = np.stack([_softmax3(s, u, c) for s,u,c in zip(s_score, u_score, c_score)], axis=0)
pred  = probs.argmax(axis=1)
ID2LAB = {0:"supports", 1:"unrelated", 2:"contradicts"}
cap_lab = np.array([ID2LAB[i] for i in pred], dtype=object)
cap_pr  = probs.copy()

# apply hard overrides
cap_lab[hard_support] = "supports"
cap_pr[hard_support]  = np.array([0.80, 0.10, 0.10])
cap_lab[hard_contra]  = "contradicts"
cap_pr[hard_contra]   = np.array([0.10, 0.10, 0.80])

# --- optional: blend confident Vision-LLM if present ---
if "vllm_label" in df.columns and "vllm_probs" in df.columns:
    vlab = df["vllm_label"].astype(str).to_numpy()
    vprs = df["vllm_probs"].apply(lambda x: np.array(x, float) if isinstance(x,(list,tuple)) else np.array([np.nan,np.nan,np.nan])).to_numpy()
    for i in range(len(df)):
        vp = vprs[i]
        if vp.size == 3 and np.isfinite(vp).all():
            vi = int(np.argmax(vp))
            if vp[vi] >= 0.65 and ID2LAB[vi] in {"supports","contradicts"}:
                cap_lab[i] = ID2LAB[vi]
                cap_pr[i]  = 0.5*cap_pr[i] + 0.5*vp  # blend for calibration

# --- rebalance safeguard (avoid >90% single class) ---
mix = pd.Series(cap_lab).value_counts(normalize=True)
if mix.max() > 0.90 and "unrelated" in mix.index:
    z = 0.6*bc_sup + 0.2*ti_sup - 0.2*dc_con - 0.2*bc_con
    q30, q70 = np.quantile(z, [0.30, 0.70])
    cap_lab[:] = np.where(z <= q30, "contradicts",
                  np.where(z >= q70, "supports", "unrelated"))
    s = np.clip((z - q30) / max(1e-6, (q70 - q30)), 0, 1)
    u = np.clip(1 - 2*np.abs(s-0.5), 0, 1)
    c = 1 - s
    cap_pr = np.stack([s, u, c], axis=1)
    cap_pr = (cap_pr.T / (cap_pr.sum(axis=1) + 1e-9)).T

# --- write back ---
df["caption_label"]      = pd.Series(cap_lab, index=df.index)
df["caption_confidence"] = pd.Series(cap_pr.max(axis=1), index=df.index)
df["caption_probs"]      = pd.Series([p.tolist() for p in cap_pr], index=df.index)

print("✅ caption_label rebuilt with tighter bands + hard rules.")
print("Mix:", pd.Series(df['caption_label']).value_counts(normalize=True).round(3).to_dict())
print("Bands:",
      f"BC_SUP={BC_SUP:.3f} / BC_CON={BC_CON:.3f}; "
      f"BL_SUP={BL_SUP:.3f} / BL_CON={BL_CON:.3f}; "
      f"RL_SUP={RL_SUP:.3f} / RL_CON={RL_CON:.3f}; "
      f"TI_SUP={TI_SUP:.2f} / TI_CON={TI_CON:.2f}; "
      f"ΔSTRONG sup≈{DC_STRONG_SUP:.3f} contra≈{DC_STRONG_CON:.3f}")

# ============================================================
# 🔀 Multimodal Fusion → MMCR probabilities & labels + Visualization + Save (tight bands)
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# ---------------------- Preconditions / scaffolding ----------------------
if 'df' not in globals():
    raise RuntimeError("`df` not found. Make sure your data loading + BLIP/CLIP steps ran and created `df`.")

required = ["bert_cosine","bleu","rougeL","clip_title_image"]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}. Run the BLIP/CLIP text-sim & CLIP similarity steps first.")

# If caption-image similarity missing, create placeholder; derive delta if missing
if "clip_caption_image" not in df.columns:
    df["clip_caption_image"] = np.nan
if "delta_clip" not in df.columns:
    df["delta_clip"] = pd.to_numeric(df["clip_title_image"], errors="coerce") - pd.to_numeric(df["clip_caption_image"], errors="coerce")

# If label_name missing but 6_way_label exists, derive for old plot compatibility
if "label_name" not in df.columns and "6_way_label" in df.columns:
    ID2NAME_6 = {0:"true",1:"satire",2:"parody",3:"misleading",4:"false_connection",5:"fabricated"}
    try:
        if pd.api.types.is_numeric_dtype(df["6_way_label"]):
            df["label_name"] = df["6_way_label"].astype(int).map(ID2NAME_6)
        else:
            df["label_name"] = df["6_way_label"].astype(str)
    except Exception:
        pass

# ---------------------- Helpers ----------------------
def _pct(v, q, default):
    v = np.asarray(v, float)
    v = v[np.isfinite(v)]
    if v.size < 10:
        return float(default)
    return float(np.percentile(v, q))

def _minmax_band_vec(x, lo, hi, fill=0.5):
    x = np.asarray(x, float)
    out = np.full_like(x, fill, dtype=float)
    msk = np.isfinite(x)
    den = max(1e-6, float(hi - lo))
    out[msk] = np.clip((x[msk] - lo) / den, 0.0, 1.0)
    return out

def _softmax3_vec(s, u, c, temp=1.3):
    v = np.stack([s, u, c], axis=-1).astype(float)
    v = v / max(1e-9, float(temp))
    v = np.exp(v - np.max(v, axis=-1, keepdims=True))
    v = v / np.clip(np.sum(v, axis=-1, keepdims=True), 1e-9, None)
    return v  # (N,3) as [p_sup, p_unrel, p_contra]

# ---------------------- Pull arrays ----------------------
bc = pd.to_numeric(df["bert_cosine"], errors="coerce").fillna(0.0).to_numpy()
bl = pd.to_numeric(df["bleu"],        errors="coerce").fillna(0.0).to_numpy()
rl = pd.to_numeric(df["rougeL"],      errors="coerce").fillna(0.0).to_numpy()
ti = pd.to_numeric(df["clip_title_image"],   errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()
ci = pd.to_numeric(df["clip_caption_image"], errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()
dc = pd.to_numeric(df["delta_clip"],         errors="coerce").replace([np.inf,-np.inf], np.nan).to_numpy()

# If delta is entirely NaN but we have ti/ci, recompute
if np.isnan(dc).all() and ("clip_title_image" in df.columns and "clip_caption_image" in df.columns):
    dc = (pd.Series(ti).astype(float) - pd.Series(ci).astype(float)).to_numpy()

# ---------------------- Tightened adaptive bands ----------------------
# Text bands (tighter → fewer easy supports)
BC_SUP = max(0.85, _pct(bc, 85, 0.82))
BC_CON = min(0.50, _pct(bc, 35, 0.45))

BL_SUP = max(0.25, _pct(bl, 80, 0.22))
BL_CON = min(0.06,  _pct(bl, 25, 0.05))

RL_SUP = max(0.30, _pct(rl, 80, 0.28))
RL_CON = min(0.06,  _pct(rl, 25, 0.05))

# Visual bands for title↔image (tighter highs/lows)
ti_fin = ti[np.isfinite(ti)]
TI_SUP = _pct(ti_fin, 80, 24.5)
TI_CON = _pct(ti_fin, 20, 20.0)

# Delta bands (title vs caption fit on image)
valid_dc = (ti - ci)[np.isfinite(ti) & np.isfinite(ci)]
if valid_dc.size >= 20:
    q25, q75 = np.percentile(valid_dc, [25, 75])
    IQR = max(1e-6, q75 - q25)
    DC_POS = +0.25 * IQR   # title≥caption → support help
    DC_NEG = -0.75 * IQR   # caption≫title → strong contra
else:
    DC_POS, DC_NEG = 0.5, -1.0

# ---------------------- Normalize to [0,1] channels ----------------------
# Text support channels (contradiction is 1 - support)
bc_sup = _minmax_band_vec(bc, BC_CON, BC_SUP);   bc_con = 1.0 - bc_sup
bl_sup = _minmax_band_vec(bl, BL_CON, BL_SUP);   bl_con = 1.0 - bl_sup
rl_sup = _minmax_band_vec(rl, RL_CON, RL_SUP);   rl_con = 1.0 - rl_sup

# Visual support/contra (title↔image)
ti_sup = _minmax_band_vec(ti, TI_CON, TI_SUP, fill=0.5);  ti_con = 1.0 - ti_sup

# Delta support/contra
dc_sup = _minmax_band_vec(dc, 0.0,  max(DC_POS, 1e-3), fill=0.5)
dc_con = _minmax_band_vec(-dc, 0.0, max(-DC_NEG,1e-3), fill=0.5)

# ---------------------- Weighted fusion ----------------------
w_bc, w_bl, w_rl, w_ti, w_dc = 0.35, 0.15, 0.15, 0.20, 0.15
mmcr_support = w_bc*bc_sup + w_bl*bl_sup + w_rl*rl_sup + w_ti*ti_sup + w_dc*dc_sup
mmcr_contra  = w_bc*bc_con + w_bl*bl_con + w_rl*rl_con + w_ti*ti_con + w_dc*dc_con

# Unrelated peaks when support≈contra and both moderate
mmcr_unrel = 1.0 - np.minimum(1.0, np.abs(mmcr_support - mmcr_contra) + 0.30*(mmcr_support + mmcr_contra))

# Softmax → probabilities & labels
probs   = _softmax3_vec(mmcr_support, mmcr_unrel, mmcr_contra, temp=1.3)  # (N,3)
pred_id = probs.argmax(axis=1)
ID2LAB3 = {0:"supports", 1:"unrelated", 2:"contradicts"}

# Write outputs
df["mmcr_score_support"]   = mmcr_support
df["mmcr_score_unrelated"] = mmcr_unrel
df["mmcr_score_contra"]    = mmcr_contra
df["mmcr_probs"]           = [p.tolist() for p in probs]
df["mmcr_label"]           = [ID2LAB3[i] for i in pred_id]
df["mmcr_confidence"]      = probs.max(axis=1)

print("✅ Added multimodal fusion fields:",
      ["mmcr_score_support","mmcr_score_unrelated","mmcr_score_contra","mmcr_probs","mmcr_label","mmcr_confidence"])

print("\n🔧 Thresholds (tight/adaptive):")
print(f"  BERT cosine: SUP≥{BC_SUP:.2f}  CON≤{BC_CON:.2f}")
print(f"  BLEU:        SUP≥{BL_SUP:.2f}  CON≤{BL_CON:.2f}")
print(f"  ROUGE-L:     SUP≥{RL_SUP:.2f}  CON≤{RL_CON:.2f}")
print(f"  CLIP t↔img:  SUP≥{TI_SUP:.2f}  CON≤{TI_CON:.2f}")
print(f"  ΔCLIP (t - c): POS≈{DC_POS:.3f}  NEG≈{DC_NEG:.3f}")

# ---------------------- Calibration (if GT exists) ----------------------
GT_MAP_6to3 = {
    "true":"supports", "satire":"unrelated", "parody":"unrelated",
    "misleading":"contradicts", "false_connection":"contradicts", "fabricated":"contradicts"
}

if "6_way_label" in df.columns:
    try:
        lab_raw = df["6_way_label"]
        if pd.api.types.is_numeric_dtype(lab_raw):
            label_name = lab_raw.astype(int).map({0:"true",1:"satire",2:"parody",3:"misleading",4:"false_connection",5:"fabricated"})
        else:
            label_name = lab_raw.astype(str)
        y_true_3 = label_name.map(GT_MAP_6to3)

        m = y_true_3.isin(["supports","unrelated","contradicts"]) & df["mmcr_probs"].notna()
        y_true_3 = y_true_3[m]
        P = np.stack(df.loc[m, "mmcr_probs"].apply(lambda x: np.array(x, float)).to_numpy())
        lab2id3 = {"supports":0, "unrelated":1, "contradicts":2}
        y_int = y_true_3.map(lab2id3).to_numpy()

        # Brier score (multiclass)
        y_onehot = np.eye(3)[y_int]
        brier = float(np.mean(np.sum((P - y_onehot)**2, axis=1)))
        print(f"\n📏 Brier score (multiclass): {brier:.4f}")

        # ECE (pred-class confidence)
        def ece_multiclass(probs, y, n_bins=15):
            conf = probs.max(axis=1)
            pred = probs.argmax(axis=1)
            acc  = (pred == y).astype(float)
            bins = np.linspace(0.0, 1.0, n_bins+1)
            ece  = 0.0
            for i in range(n_bins):
                lo, hi = bins[i], bins[i+1]
                msk = (conf >= lo) & (conf < hi) if i < n_bins-1 else (conf >= lo) & (conf <= hi)
                if not np.any(msk): continue
                ece += (msk.mean()) * abs(acc[msk].mean() - conf[msk].mean())
            return float(ece)

        ece = ece_multiclass(P, y_int, n_bins=15)
        print(f"📐 ECE (pred-class confidence): {ece:.4f}")

        # Reliability diagram
        try:
            bins = np.linspace(0,1,11)
            conf = P.max(axis=1)
            pred = P.argmax(axis=1)
            acc  = (pred == y_int).astype(float)
            digit = np.digitize(conf, bins) - 1
            xs, ys, ws = [], [], []
            for k in range(len(bins)-1):
                mask = (digit == k)
                if mask.sum() == 0: continue
                xs.append(conf[mask].mean())
                ys.append(acc[mask].mean())
                ws.append(mask.mean())
            plt.figure(figsize=(4,4))
            plt.plot([0,1],[0,1],'--', label="Perfect")
            plt.scatter(xs, ys, s=np.array(ws)*800+10, alpha=0.8)
            plt.xlabel("Confidence"); plt.ylabel("Accuracy"); plt.title("Reliability (MMCR)")
            plt.grid(alpha=0.3); plt.tight_layout(); plt.show()
        except Exception:
            pass

    except Exception as e:
        print(f"(Calibration skipped: {e})")

# ---------------------- Visualization ----------------------
# Old view: BERT-cosine by 6-way class
if {"label_name","bert_cosine"}.issubset(df.columns):
    plt.figure(figsize=(8,5))
    sns.boxplot(x="label_name", y="bert_cosine", data=df, palette="Set2")
    plt.xticks(rotation=30)
    plt.ylabel("BERT cosine (title vs BLIP caption)")
    plt.title("Semantic alignment per 6-way label")
    plt.tight_layout()
    plt.show()
else:
    print("ℹ️ Skipping old view: need ['label_name','bert_cosine'].")

# New: caption_label distribution (if you created caption_label earlier)
if "caption_label" in df.columns:
    plt.figure(figsize=(4,3))
    order3 = ["supports","unrelated","contradicts"]
    df["caption_label"].value_counts().reindex(order3).fillna(0).plot(kind="bar")
    plt.title("caption_label distribution (text + CLIP)")
    plt.xticks(rotation=0); plt.tight_layout(); plt.show()

# New: mmcr_label distribution
if "mmcr_label" in df.columns:
    plt.figure(figsize=(4,3))
    order3 = ["supports","unrelated","contradicts"]
    df["mmcr_label"].value_counts().reindex(order3).fillna(0).plot(kind="bar")
    plt.title("MMCR fused labels")
    plt.xticks(rotation=0); plt.tight_layout(); plt.show()

# ---------------------- Save ----------------------
OUT_DIR = Path("/content/drive/MyDrive/MMCR_Fakeddit_Outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)
save_path = OUT_DIR / "caption_alignment_metrics.csv"
df.to_csv(save_path, index=False)
print(f"\n💾 Saved results to: {save_path}")

present = [c for c in [
    "clip_title_image", "clip_caption_image", "delta_clip",
    "caption_label", "caption_confidence", "caption_probs",
    "mmcr_score_support","mmcr_score_unrelated","mmcr_score_contra",
    "mmcr_probs","mmcr_label","mmcr_confidence",
    "caption_alignment","label_name"
] if c in df.columns]
print("Available columns:", present)

# ===========================================================
# 👀 Conflict-Preview: show a few examples for MANY MODES
# ===========================================================
import math, textwrap
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from pathlib import Path
from PIL import Image

assert "df" in globals(), "df not found — run the pipeline cells first."

# ---------- configuration ----------
MODES   = [
    "mmcr_supports",
    "mmcr_contradicts",
    "caption_supports",
    "caption_unrelated",
    "caption_contradicts",
    "high_mismatch",      # caption explains image >> title (delta_clip very negative)
    "low_ti_high_ci",     # false-connection suspects
]
K_PER   = 3              # show this many per mode (2–3 is good)
SAVE_CSV = True
OUT_DIR  = Path("/content/drive/MyDrive/MMCR_Fakeddit_Outputs/preview_sets")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ---------- small utilities ----------
def _wrap(s, width):
    s = "" if pd.isna(s) else str(s)
    return "\n".join(textwrap.wrap(s, width=width)) if s else ""

def _header_line(row):
    cap = row.get("caption_label", np.nan); capc = row.get("caption_confidence", np.nan)
    mm  = row.get("mmcr_label", np.nan);    mmc  = row.get("mmcr_confidence", np.nan)
    vll = row.get("vllm_label", np.nan)
    cap_str = f"CAP:{cap}({capc:.2f})" if pd.notna(cap) else "CAP:–"
    mmc_str = f"MMCR:{mm}({mmc:.2f})" if pd.notna(mm) else "MMCR:–"
    vll_str = f"VLLM:{vll}" if pd.notna(vll) else "VLLM:–"
    bc  = row.get("bert_cosine", np.nan); bl = row.get("bleu", np.nan); rl = row.get("rougeL", np.nan)
    ti  = row.get("clip_title_image", np.nan); ci = row.get("clip_caption_image", np.nan); dc = row.get("delta_clip", np.nan)
    sig = f"bc:{bc:.2f} bl:{bl:.2f} rl:{rl:.2f} | TI:{ti:.2f} CI:{ci:.2f} Δ:{dc:.2f}"
    return f"{cap_str} | {mmc_str} | {vll_str}\n{sig}"

def _select_sample(df_in, mode, k):
    """Return a small dataframe slice according to 'mode'."""
    # base pool: must have local image + a caption string
    pool = df_in.copy()
    pool = pool[pool["drive_path"].astype(str).str.len() > 0]
    pool = pool[pool["blip_caption"].astype(str).str.len() > 0]
    if pool.empty:
        return pool

    # robust numeric columns
    ti = pd.to_numeric(pool["clip_title_image"], errors="coerce")
    ci = pd.to_numeric(pool.get("clip_caption_image", pd.Series(np.nan, index=pool.index)), errors="coerce")
    dc = pd.to_numeric(pool.get("delta_clip", pd.Series(np.nan, index=pool.index)), errors="coerce")

    # thresholds (computed per pool for adaptivity)
    ti_fin = ti.dropna()
    TI_LOW  = float(np.percentile(ti_fin, 25)) if len(ti_fin) >= 10 else 20.0
    ci_fin  = ci.dropna()
    CI_HIGH = float(np.percentile(ci_fin, 75)) if len(ci_fin) >= 10 else (ti_fin.median() if len(ti_fin) else 24.0)

    if mode == "random":
        return pool.sample(min(k, len(pool)), random_state=42)

    if mode == "caption_supports":
        return pool[pool.get("caption_label","").eq("supports")].head(k)

    if mode == "caption_unrelated":
        return pool[pool.get("caption_label","").eq("unrelated")].head(k)

    if mode == "caption_contradicts":
        return pool[pool.get("caption_label","").eq("contradicts")].head(k)

    if mode == "mmcr_supports":
        if "mmcr_label" in pool.columns:
            s = pool[pool["mmcr_label"].eq("supports")].head(k)
            return s if len(s) else pool[pool.get("caption_label","").eq("supports")].head(k)
        return pool[pool.get("caption_label","").eq("supports")].head(k)

    if mode == "mmcr_contradicts":
        if "mmcr_label" in pool.columns:
            s = pool[pool["mmcr_label"].eq("contradicts")].head(k)
            return s if len(s) else pool[pool.get("caption_label","").eq("contradicts")].head(k)
        return pool[pool.get("caption_label","").eq("contradicts")].head(k)

    if mode == "high_mismatch":
        # most negative delta_clip first
        return pool.sort_values("delta_clip").head(k)

    if mode == "low_ti_high_ci":
        m = (ti <= TI_LOW) & (ci >= CI_HIGH)
        return pool[m].sort_values(["clip_title_image","clip_caption_image"]).head(k)

    raise ValueError(f"Unknown MODE: {mode}")

# ---------- render per-mode ----------
all_slices = []
for mode in MODES:
    sample = _select_sample(df, mode, K_PER)
    if sample.empty:
        print(f"⚠️  No rows for MODE='{mode}'.")
        continue

    # 1) tiny table
    cols = [
        "clean_title","blip_caption","drive_path",
        *(["caption_label","caption_confidence","cap_p_sup","cap_p_unr","cap_p_con"] if "caption_label" in sample.columns else []),
        *(["mmcr_label","mmcr_confidence","mmcr_p_sup","mmcr_p_unr","mmcr_p_con"] if "mmcr_label" in sample.columns else []),
        "bert_cosine","bleu","rougeL","clip_title_image","clip_caption_image","delta_clip",
        *(["gt_conflict"] if "gt_conflict" in sample.columns else []),
    ]
    disp_cols = [c for c in cols if c in sample.columns]
    print(f"\n===== MODE: {mode}  (showing {len(sample)} rows) =====")
    display(sample[disp_cols].head(len(sample)))

    # 2) thumbnails
    num  = len(sample)
    cols = min(3, num)  # up to 3 per row
    rows = math.ceil(num / cols)
    plt.figure(figsize=(cols*6.2, rows*7.0))
    for i, row in sample.reset_index(drop=True).iterrows():
        ax = plt.subplot(rows, cols, i+1)
        try:
            img = Image.open(str(row["drive_path"])).convert("RGB")
            ax.imshow(img); ax.axis("off")
            txt = _header_line(row) + "\n" + f"T: {_wrap(row['clean_title'], 70)}\nC: {_wrap(row['blip_caption'], 70)}"
            ax.set_title(txt, fontsize=8, loc="left")
        except Exception as e:
            ax.axis("off")
            ax.set_title(f"[load error] {e}", fontsize=9)
    plt.suptitle(f"Conflict-aware preview — {mode}", fontsize=14)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()

    # collect for optional export
    all_slices.append(sample.assign(__mode__=mode))

# 3) save CSV of all slices (stacked)
if SAVE_CSV and all_slices:
    out = pd.concat(all_slices, ignore_index=True)
    out_path = OUT_DIR / f"conflict_preview_multi_{K_PER}each.csv"
    out.to_csv(out_path, index=False)
    print(f"📄 Saved combined preview slices to: {out_path}")

# ============================
# CLIP + NLI Fusion Evaluation (lean)
# ============================
import os, numpy as np, pandas as pd
from PIL import Image
import torch
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from transformers import CLIPProcessor, CLIPModel
from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# --- 0) Filter rows we can actually evaluate (image exists) ---
df_eval = df.copy()
df_eval = df_eval[df_eval["drive_path"].astype(str).str.len() > 0]
df_eval = df_eval[df_eval["drive_path"].apply(lambda p: os.path.exists(p))]
df_eval = df_eval.reset_index(drop=True)
print("Rows with existing image files:", len(df_eval))

# Ensure we have a caption column (use empty if not)
if "blip_caption" not in df_eval.columns:
    df_eval["blip_caption"] = ""

# --- 1) CLIP similarities (title↔image, caption↔image) ---
clip_name = "openai/clip-vit-large-patch14"
clip_proc  = CLIPProcessor.from_pretrained(clip_name)
clip_model = CLIPModel.from_pretrained(clip_name).to(device).eval()

@torch.no_grad()
def clip_sim_one(text, img_path):
    try:
        img = Image.open(img_path).convert("RGB")
        batch = clip_proc(text=[str(text)], images=[img], return_tensors="pt", padding=True).to(device)
        out = clip_model(**batch)
        return out.logits_per_image.squeeze().item()
    except Exception:
        return np.nan

print("Computing CLIP(title,image) & CLIP(caption,image)...")
df_eval["clip_title_image"] = [
    clip_sim_one(t, p) for t, p in tqdm(zip(df_eval["clean_title"], df_eval["drive_path"]), total=len(df_eval))
]
df_eval["clip_caption_image"] = [
    clip_sim_one(c if isinstance(c,str) and c.strip() else "", p)
    for c, p in tqdm(zip(df_eval["blip_caption"].fillna(""), df_eval["drive_path"]), total=len(df_eval))
]

# --- 2) NLI (title vs. BLIP caption) ---
nli_name  = "roberta-large-mnli"
nli_tok   = AutoTokenizer.from_pretrained(nli_name)
nli_model = AutoModelForSequenceClassification.from_pretrained(nli_name).to(device).eval()
id2lab = {0:"contradiction", 1:"neutral", 2:"entailment"}

@torch.no_grad()
def nli_pair(premise, hypothesis):
    hyp = hypothesis if (isinstance(hypothesis,str) and hypothesis.strip()) else ""
    toks = nli_tok.encode_plus(str(premise), hyp, return_tensors="pt", truncation=True, max_length=512).to(device)
    logits = nli_model(**toks).logits
    probs = torch.softmax(logits, dim=-1).squeeze().tolist()
    return id2lab[int(np.argmax(probs))], probs  # [pC, pN, pE]

print("Running NLI title vs. caption...")
nli_labels, pC, pN, pE = [], [], [], []
for t, c in tqdm(zip(df_eval["clean_title"], df_eval["blip_caption"].fillna("")), total=len(df_eval)):
    lab, pr = nli_pair(t, c)
    nli_labels.append(lab); pC.append(pr[0]); pN.append(pr[1]); pE.append(pr[2])

df_eval["nli_label"] = nli_labels
df_eval["nli_pC"] = pC
df_eval["nli_pN"] = pN
df_eval["nli_pE"] = pE

# --- 3) Adaptive thresholds + fusion → {supports, unrelated, contradicts}
valid = df_eval["clip_title_image"].replace([np.inf,-np.inf], np.nan).dropna()
LOW_SIM  = float(np.percentile(valid, 25)) if len(valid) >= 5 else 20.0
HIGH_SIM = float(np.percentile(valid, 75)) if len(valid) >= 5 else 24.0
print(f"Adaptive CLIP thresholds: LOW_SIM={LOW_SIM:.3f}, HIGH_SIM={HIGH_SIM:.3f}")

def fuse(nli_lab, clip_ti, p_contra, p_ent):
    if nli_lab == "contradiction" or (p_contra is not None and p_contra >= 0.6):
        return "contradicts"
    if (nli_lab == "entailment" or (p_ent is not None and p_ent >= 0.6)) and (clip_ti is not None and clip_ti >= HIGH_SIM):
        return "supports"
    if (clip_ti is not None) and (clip_ti < LOW_SIM):
        return "contradicts"
    return "unrelated"

df_eval["pred_conflict"] = [
    fuse(nl, s, pc, pe) for nl, s, pc, pe in zip(df_eval["nli_label"], df_eval["clip_title_image"], df_eval["nli_pC"], df_eval["nli_pE"])
]

# --- 4) Gold 3-way mapping from 6-way labels
ID2NAME = {0:"true", 1:"satire", 2:"parody", 3:"misleading", 4:"false_connection", 5:"fabricated"}
df_eval["label_name"] = df_eval["6_way_label"].astype(int).map(ID2NAME)

GT_MAP = {"true":"supports","satire":"unrelated","parody":"unrelated",
          "misleading":"contradicts","false_connection":"contradicts","fabricated":"contradicts"}
df_eval["gt_conflict"] = df_eval["label_name"].map(GT_MAP).fillna("unrelated")

# --- 5) Metrics (robust to missing classes) ---
name2id = {"supports":0, "unrelated":1, "contradicts":2}
id2name = {v:k for k,v in name2id.items()}
mask   = df_eval["gt_conflict"].isin(name2id) & df_eval["pred_conflict"].isin(name2id)
y_true = df_eval.loc[mask, "gt_conflict"].map(name2id).to_numpy()
y_pred = df_eval.loc[mask, "pred_conflict"].map(name2id).to_numpy()

present = sorted(np.unique(np.concatenate([y_true, y_pred]))) if len(y_true) else []
present_names = [id2name[i] for i in present]

print("\n=== 3-way Conflict Metrics (supports/unrelated/contradicts) ===")
if len(y_true):
    acc      = accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average="macro", labels=present)
    micro_f1 = f1_score(y_true, y_pred, average="micro", labels=present)
    print(f"Accuracy : {acc:.4f}")
    print(f"Macro F1 : {macro_f1:.4f}")
    print(f"Micro F1 : {micro_f1:.4f}\n")
    print(classification_report(y_true, y_pred, labels=present, target_names=present_names, zero_division=0))
else:
    print("No comparable examples after filtering.")

# --- 6) Confusion matrix (only if ≥2 present classes) ---
if len(y_true) and len(present) >= 2:
    cm = confusion_matrix(y_true, y_pred, labels=present)
    plt.figure(figsize=(5,4))
    plt.imshow(cm, interpolation='nearest')
    plt.title("Confusion Matrix (present classes)")
    plt.colorbar()
    plt.xticks(range(len(present)), present_names, rotation=45)
    plt.yticks(range(len(present)), present_names)
    th = cm.max()/2 if cm.max()>0 else 1
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            v = cm[i,j]
            plt.text(j, i, str(v), ha="center", va="center", color=("white" if v>th else "black"))
    plt.tight_layout()
    plt.show()

# ===========================================================
# 👀 Preview CLIP+NLI Fusion — ALL MODES (no graphs)
# ===========================================================
import math
from pathlib import Path
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from PIL import Image

assert 'df_eval' in globals(), "df_eval not found — run the CLIP+NLI fusion cell first."

# ------- config -------
MODES = [
    "random",
    "top_supports",
    "top_contradicts",
    "high_clip",
    "high_entailment",
    "high_contradiction",
    # include only if you have vLLM columns:
    "disagree_with_vllm",
]
N_SHOW_PER_MODE = 3
SAVE_CSV = True
OUT_DIR = Path("/content/drive/MyDrive/MMCR_Fakeddit_Outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)
# ----------------------

# ---- checks ----
needed = ["pred_conflict", "clip_title_image", "nli_pE", "nli_pC", "nli_label", "drive_path"]
missing = [c for c in needed if c not in df_eval.columns]
if missing:
    raise ValueError(f"Missing columns in df_eval: {missing}. Run the fusion cell first.")

# ---- prep once ----
df_vis = df_eval.copy()
df_vis = df_vis[df_vis["drive_path"].astype(str).str.len() > 0]
df_vis = df_vis[df_vis["pred_conflict"].isin(["supports","unrelated","contradicts"])]

clip_norm = df_vis["clip_title_image"].replace([np.inf,-np.inf], np.nan)
clip_norm = (clip_norm - clip_norm.min()) / (clip_norm.max() - clip_norm.min() + 1e-9)
df_vis = df_vis.assign(
    proxy_support    = 0.7 * clip_norm + 0.3 * df_vis["nli_pE"].astype(float),
    proxy_contradict = 0.7 * (1.0 - clip_norm) + 0.3 * df_vis["nli_pC"].astype(float),
    proxy_confidence = np.maximum(df_vis["nli_pE"].astype(float), df_vis["nli_pC"].astype(float)),
)

def _select_sample(dfv, mode, k):
    if mode == "random":
        return dfv.sample(min(k, len(dfv)), random_state=42)
    if mode == "top_supports":
        return dfv.sort_values("proxy_support", ascending=False).head(k)
    if mode == "top_contradicts":
        return dfv.sort_values("proxy_contradict", ascending=False).head(k)
    if mode == "high_clip":
        return dfv.sort_values("clip_title_image", ascending=False).head(k)
    if mode == "high_entailment":
        return dfv.sort_values("nli_pE", ascending=False).head(k)
    if mode == "high_contradiction":
        return dfv.sort_values("nli_pC", ascending=False).head(k)
    if mode == "disagree_with_vllm":
        if "vllm_label" not in dfv.columns:
            raise ValueError("vllm_label not found.")
        sub = dfv[dfv["vllm_label"] != dfv["pred_conflict"]]
        if len(sub) == 0:
            raise ValueError("No disagreements between CLIP+NLI and Vision-LLM.")
        return sub.sort_values("proxy_confidence", ascending=False).head(k)
    raise ValueError(f"Unknown MODE: {mode}")

def _show(ax, path, title):
    try:
        img = Image.open(path).convert("RGB")
        ax.imshow(img); ax.axis("off"); ax.set_title(title, fontsize=9)
    except Exception as e:
        ax.axis("off"); ax.set_title(f"[load error]\n{e}", fontsize=9)

# ===== iterate all modes =====
for MODE in MODES:
    try:
        sample = _select_sample(df_vis, MODE, N_SHOW_PER_MODE)
        if sample.empty:
            print(f"⚠️ MODE='{MODE}': no rows found; skipping.")
            continue
    except Exception as e:
        print(f"⚠️ MODE='{MODE}': {e}; skipping.")
        continue

    print(f"\n=== MODE: {MODE} (N={len(sample)}) ===")
    table_cols = [c for c in [
        "pred_conflict","clip_title_image","nli_label","nli_pE","nli_pC",
        "gt_conflict" if "gt_conflict" in sample.columns else None,
        "vllm_label"  if "vllm_label"  in sample.columns else None,
        "clean_title","drive_path"
    ] if c]
    display(sample[table_cols])

    # small image grid (2–3 examples)
    num = len(sample)
    cols = min(3, num)
    rows = math.ceil(num / cols)
    plt.figure(figsize=(cols*4.0, rows*4.5))
    for i, row in sample.reset_index(drop=True).iterrows():
        ax = plt.subplot(rows, cols, i+1)
        ttl = f"{row['pred_conflict']}\nCLIP:{row['clip_title_image']:.2f}  NLI(E:{row['nli_pE']:.2f}/C:{row['nli_pC']:.2f})"
        _show(ax, row["drive_path"], ttl)
    plt.suptitle(f"CLIP+NLI — {MODE}", fontsize=13)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

    # save slice per mode
    if SAVE_CSV:
        out_path = OUT_DIR / f"clip_nli_preview_{MODE}.csv"
        sample.to_csv(out_path, index=False)
        print(f"📄 Saved slice: {out_path}")

"""
## Next steps & notes
- **Threshold tuning**: Inspect histogram/scatter plots and adjust `LOW_SIM`/`HIGH_SIM`.  
- **Better captions**: Use BLIP-2, InstructBLIP, or modern captioners for richer descriptions.  
- **Vision-LLM judgment**: Replace the NLI step with a vision-LMM (e.g., LLaVA, IDEFICS, GPT-4V) to judge *directly* whether the image supports the title.  
- **Calibration**: Add ECE/Brier calibration curves for probabilities.  
- **Fusion**: Swap heuristic with logistic regression or a tiny MLP over features: `[clip_sim, nli_probs...]` trained on validation.
"""

# ============================
# Vision-LLM Judgment (3-way)
# ============================
# Replaces the NLI step. Produces:
#  - df_eval['vllm_label'] in {"supports","unrelated","contradicts"}
#  - df_eval['vllm_probs']  as [p_sup, p_unrel, p_contra]
#
# Backends: set VLLM_BACKEND to "llava" or "idefics2".
# If you only want to wire quickly, set DRY_RUN=True.

import re, json, torch
from typing import Tuple, Dict, Any
from PIL import Image
from transformers import AutoModelForCausalLM, AutoProcessor, BitsAndBytesConfig

VLLM_BACKEND = "llava"         # "llava" or "idefics2"
LLAVA_MODEL_ID   = "llava-hf/llava-1.5-7b-hf"
IDEFICS_MODEL_ID = "HuggingFaceM4/idefics2-8b"
DRY_RUN = False

device = "cuda" if torch.cuda.is_available() else "cpu"
_vllm_model = None
_vllm_proc  = None

def _load_vllm():
    global _vllm_model, _vllm_proc
    if DRY_RUN:
        return
    if _vllm_model is not None:
        return
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)
    model_id = LLAVA_MODEL_ID if VLLM_BACKEND == "llava" else IDEFICS_MODEL_ID
    _vllm_model = AutoModelForCausalLM.from_pretrained(
        model_id, torch_dtype=torch.float16, device_map="auto", quantization_config=bnb
    )
    _vllm_proc  = AutoProcessor.from_pretrained(model_id)

SYSTEM_PROMPT = (
    "You are a careful fact judge. Read the TITLE and look at the IMAGE.\n"
    "Return strict JSON with keys: label, probs. The label must be one of "
    '["supports","contradicts","unrelated"]. The probs must be an object with keys '
    'supports, unrelated, contradicts whose values are non-negative and sum to 1.0.'
)

USER_TEMPLATE = (
    "TITLE: {title}\n"
    "Task: Considering the image, decide if it supports, contradicts, or is unrelated to the TITLE.\n"
    "Return EXACT JSON only.\n"
    '{"label": "...", "probs": {"supports": p1, "unrelated": p2, "contradicts": p3}}'
)

def _safe_parse_vllm_json(text: str) -> Tuple[str, Dict[str, float]]:
    # try to parse the last {...} JSON in text
    m = re.search(r"\{.*\}", text, flags=re.S)
    label = "unrelated"
    probs = {"supports": 1/3, "unrelated": 1/3, "contradicts": 1/3}
    if not m:
        return label, probs
    try:
        obj = json.loads(m.group(0))
        lab = str(obj.get("label","unrelated")).strip().lower()
        pr  = obj.get("probs", {})
        if lab not in {"supports","contradicts","unrelated"}:
            lab = "unrelated"
        # normalize probabilities if possible
        s = float(pr.get("supports", 0.0))
        u = float(pr.get("unrelated", 0.0))
        c = float(pr.get("contradicts", 0.0))
        total = s + u + c
        if total > 0:
            s, u, c = s/total, u/total, c/total
        else:
            s = u = c = 1/3
        probs = {"supports": s, "unrelated": u, "contradicts": c}
        return lab, probs
    except Exception:
        return label, probs

@torch.inference_mode()
def vision_llm_judge_image(image_path: str, title: str, max_new_tokens: int = 64) -> Tuple[str, Dict[str,float], str]:
    """
    Returns: (label, probs_dict, raw_text)
    """
    if DRY_RUN:
        # deterministic stub tied to title length for quick wiring
        k = len(title) % 3
        labs = ["supports","unrelated","contradicts"]
        lab = labs[k]
        pr  = {"supports": 0.6 if lab=="supports" else 0.2,
               "unrelated": 0.6 if lab=="unrelated" else 0.2,
               "contradicts": 0.6 if lab=="contradicts" else 0.2}
        return lab, pr, f'{{"label":"{lab}","probs":{pr}}}'

    _load_vllm()
    img = Image.open(image_path).convert("RGB")
    user_prompt = USER_TEMPLATE.format(title=title)

    if VLLM_BACKEND == "llava":
        prompt = f"<|system|>\n{SYSTEM_PROMPT}\n<|user|>\n{user_prompt}\n<|assistant|>\n"
        inputs = _vllm_proc(text=prompt, images=img, return_tensors="pt").to(_vllm_model.device, dtype=_vllm_model.dtype)
        out = _vllm_model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, temperature=0.0)
        raw = _vllm_proc.decode(out[0], skip_special_tokens=True)
        # Keep assistant tail if template is preserved
        raw_tail = raw.split("<|assistant|>")[-1].strip()
        lab, probs = _safe_parse_vllm_json(raw_tail)
        return lab, probs, raw_tail

    elif VLLM_BACKEND == "idefics2":
        messages = [
            {"role": "system", "content": [{"type":"text","text": SYSTEM_PROMPT}]},
            {"role": "user",   "content": [{"type":"text","text": user_prompt},
                                           {"type":"image","image": img}]}
        ]
        proc_text = _vllm_proc.apply_chat_template(messages, add_generation_prompt=True)
        inputs = _vllm_proc(text=proc_text, images=[img], return_tensors="pt").to(_vllm_model.device, dtype=_vllm_model.dtype)
        out = _vllm_model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, temperature=0.0)
        raw = _vllm_proc.batch_decode(out, skip_special_tokens=True)[0]
        lab, probs = _safe_parse_vllm_json(raw)
        return lab, probs, raw

    else:
        raise ValueError("Unsupported VLLM_BACKEND")

# ---- Run over df_eval (uses your existing df_eval from the CLIP block) ----
print("Running Vision-LLM judgment over images...")
v_labels, v_probs, v_raw = [], [], []
for title, pth in tqdm(zip(df_eval["clean_title"], df_eval["drive_path"]), total=len(df_eval)):
    try:
        lab, pr, raw = vision_llm_judge_image(str(pth), str(title))
    except Exception as e:
        lab, pr, raw = "unrelated", {"supports":1/3,"unrelated":1/3,"contradicts":1/3}, f"[ERROR] {e}"
    v_labels.append(lab)
    v_probs.append([pr["supports"], pr["unrelated"], pr["contradicts"]])
    v_raw.append(raw)

df_eval["vllm_label"] = v_labels
df_eval["vllm_probs"] = v_probs  # list of length-3
df_eval["vllm_raw"]   = v_raw

# (Optional) If you still want to fuse with CLIP thresholds, you can gate obvious cases:
# e.g., if CLIP is extremely low, push towards "contradicts"; extremely high + supports label keeps "supports".
# Otherwise, we will directly use the vllm_label as the final prediction below.

# ===========================================================
# 💾 Save Vision-LLM judgments (CSV + JSONL)
# ===========================================================
from pathlib import Path
import json

assert 'df_eval' in globals(), "df_eval not found — run the Vision-LLM cell first."

OUT_DIR = Path(globals().get('OUT_DIR', BASE_DIR)) / "mmcr_outputs"
OUT_DIR.mkdir(parents=True, exist_ok=True)

SAVE_CSV   = OUT_DIR / "vision_llm_judgments.csv"
SAVE_JSONL = OUT_DIR / "vision_llm_judgments.jsonl"

# Select useful columns if present
cols = []
for c in [
    "clean_title","drive_path","label_name","gt_conflict",
    "clip_title_image","clip_caption_image",
    "blip_caption","vllm_label","vllm_probs","vllm_raw"
]:
    if c in df_eval.columns:
        cols.append(c)

df_eval[cols].to_csv(SAVE_CSV, index=False)

with open(SAVE_JSONL, "w", encoding="utf-8") as f:
    for _, r in df_eval[cols].iterrows():
        rec = r.to_dict()
        # ensure vllm_probs is plain list, not numpy
        if isinstance(rec.get("vllm_probs"), (list, tuple)):
            rec["vllm_probs"] = [float(x) for x in rec["vllm_probs"]]
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

print(f"✅ Saved CSV:   {SAVE_CSV}")
print(f"✅ Saved JSONL: {SAVE_JSONL}")
print(f"Rows saved: {len(df_eval)}")

# ===========================================================
# 👀 Preview a few Vision-LLM results (table + thumbnails)
# ===========================================================
import math, numpy as np, pandas as pd, matplotlib.pyplot as plt
from PIL import Image

assert 'df_eval' in globals(), "df_eval not found — run the Vision-LLM cell first."

N_SHOW = 12          # how many to visualize
MODE   = "random"    # "random" | "top_supports" | "top_contradicts" | "high_confidence"

df_vis = df_eval.copy()
df_vis = df_vis[df_vis["drive_path"].astype(str).str.len() > 0]
df_vis = df_vis[df_vis["vllm_label"].isin(["supports","unrelated","contradicts"])]

# unpack probs for sorting
probs_arr = np.stack(df_vis["vllm_probs"].apply(lambda x: np.array(x, dtype=float)))
df_vis = df_vis.assign(
    p_supports   = probs_arr[:,0],
    p_unrelated  = probs_arr[:,1],
    p_contradicts= probs_arr[:,2],
    vllm_conf    = probs_arr.max(axis=1)
)

if MODE == "random":
    sample = df_vis.sample(min(N_SHOW, len(df_vis)), random_state=42)
elif MODE == "top_supports":
    sample = df_vis.sort_values("p_supports", ascending=False).head(N_SHOW)
elif MODE == "top_contradicts":
    sample = df_vis.sort_values("p_contradicts", ascending=False).head(N_SHOW)
elif MODE == "high_confidence":
    sample = df_vis.sort_values("vllm_conf", ascending=False).head(N_SHOW)
else:
    raise ValueError('MODE must be one of {"random","top_supports","top_contradicts","high_confidence"}')

# ---- quick table head
table_cols = [c for c in [
    "vllm_label","p_supports","p_unrelated","p_contradicts",
    "gt_conflict" if "gt_conflict" in sample.columns else None,
    "clean_title","drive_path"
] if c]
display(sample[table_cols].head(min(10, len(sample))))

# ---- per-class counts
plt.figure(figsize=(4,3))
sample["vllm_label"].value_counts().reindex(["supports","unrelated","contradicts"]).plot(kind="bar")
plt.title("Vision-LLM predicted labels (sample)")
plt.xticks(rotation=0); plt.tight_layout(); plt.show()

# ---- image grid with predicted label + probs
def _show(ax, path, title):
    try:
        img = Image.open(path).convert("RGB")
        ax.imshow(img)
        ax.axis("off")
        ax.set_title(title, fontsize=9)
    except Exception as e:
        ax.axis("off")
        ax.set_title(f"[load error]\n{e}", fontsize=9)

num  = len(sample)
cols = 4
rows = math.ceil(num / cols)
plt.figure(figsize=(cols*4.0, rows*4.5))
for i, row in sample.reset_index(drop=True).iterrows():
    ax = plt.subplot(rows, cols, i+1)
    ttl = f"{row['vllm_label']}\n[s:{row['p_supports']:.2f} u:{row['p_unrelated']:.2f} c:{row['p_contradicts']:.2f}]"
    _show(ax, row["drive_path"], ttl)
plt.suptitle("Vision-LLM Predictions — Sample Preview", fontsize=14)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

# =================================
# Calibration Metrics & Plot Helpers
# =================================
import numpy as np
import matplotlib.pyplot as plt

def expected_calibration_error(probs: np.ndarray, y_true: np.ndarray, n_bins: int = 15) -> float:
    """Multiclass ECE using max-prob (confidence) binning."""
    confidences = probs.max(axis=1)
    predictions = probs.argmax(axis=1)
    accuracies  = (predictions == y_true).astype(float)

    ece = 0.0
    bin_edges = np.linspace(0.0, 1.0, n_bins+1)
    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i+1]
        mask = (confidences > lo) & (confidences <= hi) if i > 0 else (confidences >= lo) & (confidences <= hi)
        if not np.any(mask):
            continue
        bin_conf = confidences[mask].mean()
        bin_acc  = accuracies[mask].mean()
        ece += (mask.mean()) * abs(bin_acc - bin_conf)
    return float(ece)

def multiclass_brier_score(probs: np.ndarray, y_true: np.ndarray, n_classes: int) -> float:
    y_onehot = np.eye(n_classes)[y_true]
    return float(np.mean(np.sum((probs - y_onehot)**2, axis=1)))

def reliability_diagram_overall(probs: np.ndarray, y_true: np.ndarray, n_bins: int = 15, title: str = "Reliability (Overall)"):
    confidences = probs.max(axis=1)
    predictions = probs.argmax(axis=1)
    accuracies  = (predictions == y_true).astype(float)

    bin_edges = np.linspace(0.0, 1.0, n_bins+1)
    xs, ys, ws = [], [], []
    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i+1]
        mask = (confidences > lo) & (confidences <= hi) if i > 0 else (confidences >= lo) & (confidences <= hi)
        if not np.any(mask):
            continue
        xs.append(np.mean(confidences[mask]))
        ys.append(np.mean(accuracies[mask]))
        ws.append(np.mean(mask))
    plt.figure(figsize=(6,6))
    plt.plot([0,1], [0,1], linestyle="--")
    plt.scatter(xs, ys, s=np.array(ws)*1000)
    plt.title(title)
    plt.xlabel("Confidence")
    plt.ylabel("Accuracy")
    plt.grid(True)
    plt.show()

def reliability_diagram_per_class(probs: np.ndarray, y_true: np.ndarray, class_names, n_bins: int = 10):
    y_onehot = np.eye(len(class_names))[y_true]
    for c, name in enumerate(class_names):
        conf = probs[:, c]
        pos  = (y_onehot[:, c] == 1).astype(float)
        bin_edges = np.linspace(0.0, 1.0, n_bins+1)
        xs, ys, ws = [], [], []
        for i in range(n_bins):
            lo, hi = bin_edges[i], bin_edges[i+1]
            mask = (conf > lo) & (conf <= hi) if i > 0 else (conf >= lo) & (conf <= hi)
            if not np.any(mask):
                continue
            xs.append(np.mean(conf[mask]))
            ys.append(np.mean(pos[mask]))   # empirical positivity
            ws.append(np.mean(mask))
        plt.figure(figsize=(6,6))
        plt.plot([0,1], [0,1], linestyle="--")
        plt.scatter(xs, ys, s=np.array(ws)*1000)
        plt.title(f"Reliability — {name} (one-vs-rest)")
        plt.xlabel("Confidence for class")
        plt.ylabel("Empirical Positivity Rate")
        plt.grid(True)
        plt.show()

# ===== Compute & Visualize calibration for the Vision-LLM =====
CLASS_NAMES_3 = ["supports","unrelated","contradicts"]
if len(y_true):
    ece   = expected_calibration_error(probs_vllm, y_true, n_bins=15)
    brier = multiclass_brier_score(probs_vllm, y_true, n_classes=3)
    print(f"[Vision-LLM] ECE: {ece:.4f} | Brier: {brier:.4f}")

    reliability_diagram_overall(probs_vllm, y_true, n_bins=15, title="Reliability (Overall) — Vision-LLM")
    reliability_diagram_per_class(probs_vllm, y_true, CLASS_NAMES_3, n_bins=10)
else:
    print("No comparable examples available for calibration plots.")

"""# ➕ PHASE 3–5 (Appended): Credibility, Calibration, Explanations, Evaluation
This section augments the existing pipeline. It keeps your dataset loading paths unchanged, and uses the same Drive directory to read/write artifacts.

**What’s inside**
1) Vision‑LLM judge **fix** (prevents uniform percentages)
2) Credibility weighting (per‑source) + Temperature scaling (ECE/Brier)
3) Explanation module (template‑guided) with text + BLIP + credibility/context
4) Evaluation & Visualization + saved artifacts in Drive

"""

# ==============================
# Paths & minimal helpers (consistent with earlier cells)
# ==============================
import os, re, ast, math, json, random
from pathlib import Path
import numpy as np
import pandas as pd
from urllib.parse import urlparse
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split

# Respect your existing base path; fall back to this common one
try:
    BASE_DIR
except NameError:
    BASE_DIR = Path('/content/drive/MyDrive/MMCR_Fakeddit_Experiment')
BASE_DIR = Path(str(BASE_DIR))
BASE_DIR.mkdir(parents=True, exist_ok=True)
DRIVE_CSV = BASE_DIR / 'eval_predictions.csv'

CLASS_NAMES = [
    'TRUE','SATIRE','FALSE CONNECTION','IMPOSTER CONTENT','MANIPULATED CONTENT','MISLEADING CONTENT'
]
NUM_CLASSES = len(CLASS_NAMES)
name_to_id = {n:i for i,n in enumerate(CLASS_NAMES)}
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED); random.seed(RANDOM_SEED)

def _to_int_label(x):
    if isinstance(x, (int, np.integer)): return int(x)
    if isinstance(x, str):
        if x.isdigit(): return int(x)
        return name_to_id.get(x.upper(), None)
    return None

def _detect_probas(df):
    if 'y_proba' in df.columns:
        P = df['y_proba'].apply(lambda x: np.array(x if not isinstance(x, str) else ast.literal_eval(x), dtype=float))
        return np.stack(P.values)
    cols = [c for c in df.columns if c.startswith('y_proba_')]
    if cols:
        cols_sorted = sorted(cols, key=lambda c: int(c.split('_')[-1]))
        return df[cols_sorted].values.astype(float)
    raise ValueError("No probability columns found: expected 'y_proba' or 'y_proba_0..K-1'.")

def _derive_source(url_or_str):
    s = str(url_or_str or '')
    try:
        netloc = urlparse(s).netloc
        return netloc.lower() if netloc else 'unknown'
    except:
        return 'unknown'

"""## 3.0 Vision‑LLM Judge — Fix for Uniform Probabilities
Some earlier variants normalized across the entire batch or reused the same vector for every row, which causes identical percentages. This cell provides **row‑wise** normalization and optional reconstruction from logits if available.
"""

def fix_vllm_scores_inplace(df, prefer_logits=True):
    """Detect uniform VLLM scores and fix them.
    Strategies:
    1) If columns 'vllm_logit_0..K-1' exist, apply per‑row softmax.
    2) Else if 'vllm_score_0..K-1' exist but many rows are uniform (std≈0), re‑normalize per‑row.
    3) If still uniform, fall back to model y_proba_* scores as a proxy for ranking.
    """
    def _cols(prefix):
        cols = [c for c in df.columns if c.startswith(prefix)]
        return sorted(cols, key=lambda x: int(x.split('_')[-1]))
    logit_cols = _cols('vllm_logit_')
    score_cols = _cols('vllm_score_')

    def _softmax(Z):
        Z = Z - Z.max(axis=1, keepdims=True)
        EZ = np.exp(Z)
        return (EZ.T / (EZ.sum(axis=1, keepdims=True)+1e-12)).T

    fixed = False
    if prefer_logits and logit_cols:
        Z = df[logit_cols].values.astype(float)
        P = _softmax(Z)
        for k in range(P.shape[1]):
            df[f'vllm_score_{k}'] = P[:,k]
        fixed = True
    elif score_cols:
        P = df[score_cols].values.astype(float)
        # Check per‑row std; if too many near‑uniform, renormalize row‑wise
        row_std = P.std(axis=1)
        if (row_std < 1e-6).mean() > 0.2:
            P = (P.T / (P.sum(axis=1)+1e-12)).T
            for k in range(P.shape[1]):
                df[f'vllm_score_{k}'] = P[:,k]
            fixed = True
    else:
        # No VLLM columns present; nothing to fix
        return False

    # Final guard: if still uniform, replace with model probabilities if present
    score_cols = _cols('vllm_score_')
    if score_cols:
        P = df[score_cols].values.astype(float)
        if (P.std(axis=1) < 1e-6).mean() > 0.2:
            mcols = _cols('y_proba_')
            if mcols:
                M = df[mcols].values.astype(float)
                M = (M.T / (M.sum(axis=1)+1e-12)).T
                for k in range(M.shape[1]):
                    df[f'vllm_score_{k}'] = M[:,k]
                fixed = True
    return fixed

# If df_eval exists, try to fix in place
if 'df_eval' in globals():
    _ = fix_vllm_scores_inplace(df_eval)
    print('Vision‑LLM judge fix applied to df_eval (if needed).')
else:
    print('df_eval not found at this point; fix will run after we load df_eval below.')

"""## 3.1 Load or Export `df_eval` Consistently
We use your in‑memory `df_eval` if present; otherwise we load the canonical CSV from Drive. We also *write back* a normalized CSV so future runs are consistent.
"""

def _ensure_probas(df):
    cols = [c for c in df.columns if c.startswith('y_proba_')]
    if 'y_proba' in df.columns and not cols:
        P = df['y_proba'].apply(lambda x: np.array(x if not isinstance(x, str) else ast.literal_eval(x), dtype=float))
        P = np.stack(P.values)
        P = (P.T / (P.sum(axis=1)+1e-12)).T
        for k in range(P.shape[1]):
            df[f'y_proba_{k}'] = P[:,k]
    else:
        # normalize split columns if present
        cols = [c for c in df.columns if c.startswith('y_proba_')]
        if cols:
            P = df[sorted(cols, key=lambda c:int(c.split('_')[-1]))].values.astype(float)
            P = (P.T / (P.sum(axis=1)+1e-12)).T
            for k in range(P.shape[1]):
                df[f'y_proba_{k}'] = P[:,k]
    return df

def _load_or_export_eval():
    if 'df_eval' in globals():
        df = df_eval.copy()
        print('Loaded df_eval from memory:', df.shape)
    elif DRIVE_CSV.exists():
        df = pd.read_csv(DRIVE_CSV)
        print('Loaded df_eval from Drive CSV:', DRIVE_CSV)
    else:
        raise FileNotFoundError('df_eval not in memory and Drive CSV not found at '+str(DRIVE_CSV))
    df = _ensure_probas(df)
    if 'y_pred' not in df.columns:
        cols = [c for c in df.columns if c.startswith('y_proba_')]
        P = df[sorted(cols, key=lambda c:int(c.split('_')[-1]))].values
        df['y_pred'] = P.argmax(axis=1)
    # derive source if missing
    if 'source' not in df.columns:
        df['source'] = df.get('image_url','').apply(_derive_source)
    # persist a clean CSV for reproducibility
    df.to_csv(DRIVE_CSV, index=False)
    print('Wrote normalized eval_predictions.csv to:', DRIVE_CSV)
    return df

df_eval_phase3 = _load_or_export_eval()
if 'vllm_score_0' in df_eval_phase3.columns or 'vllm_logit_0' in df_eval_phase3.columns:
    _ = fix_vllm_scores_inplace(df_eval_phase3)
    print('Applied Vision‑LLM judge stabilization on loaded df.')

"""## 3.2 Credibility Weighting (Per‑Source)"""

def compute_source_credibility(df, alpha=1.0):
    yt = df['6_way_label'].apply(_to_int_label).values
    yp = df['y_pred'].apply(_to_int_label).values
    src = df['source'].astype(str).values
    cred = {}
    for s in np.unique(src):
        idx = np.where(src==s)[0]
        total = len(idx)
        correct = int((yt[idx] == yp[idx]).sum())
        cred[s] = (correct + alpha) / (total + 2*alpha)
    return cred

y_true_all = df_eval_phase3['6_way_label'].apply(_to_int_label).values
P_all = _detect_probas(df_eval_phase3)

# calibration split selection
if 'split' in df_eval_phase3.columns:
    mask_cal = df_eval_phase3['split'].astype(str).str.lower().isin(['val','valid','validation','cal','calib','calibration'])
    if mask_cal.any():
        df_cal = df_eval_phase3[mask_cal].copy()
        df_test = df_eval_phase3[~mask_cal].copy()
    else:
        df_cal, df_test = train_test_split(df_eval_phase3, test_size=0.5, random_state=RANDOM_SEED, stratify=y_true_all)
else:
    df_cal, df_test = train_test_split(df_eval_phase3, test_size=0.5, random_state=RANDOM_SEED, stratify=y_true_all)

source_cred = compute_source_credibility(df_cal, alpha=1.0)
df_test['source_cred'] = df_test['source'].map(source_cred).fillna(np.mean(list(source_cred.values())))

def _probas_from(df):
    cols = [c for c in df.columns if c.startswith('y_proba_')]
    cols = sorted(cols, key=lambda c:int(c.split('_')[-1]))
    return df[cols].values.astype(float)

P_test_raw = _probas_from(df_test)
P_weighted = P_test_raw * df_test['source_cred'].values.reshape(-1,1)
P_weighted = (P_weighted.T / (P_weighted.sum(axis=1)+1e-12)).T
df_test['y_pred_weighted'] = P_weighted.argmax(axis=1)
acc_raw = accuracy_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred'])
acc_wtd = accuracy_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred_weighted'])
f1_raw  = f1_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred'], average='macro')
f1_wtd  = f1_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred_weighted'], average='macro')
print({'acc_raw': round(acc_raw,4), 'acc_weighted': round(acc_wtd,4), 'f1_raw': round(f1_raw,4), 'f1_weighted': round(f1_wtd,4)})

"""## 3.3 Temperature Scaling (Calibration) + Final Fusion"""

def _safe_logits(P, eps=1e-12):
    P = np.clip(P, eps, 1.0)
    return np.log(P)

def nll_loss(P, y):
    P = np.clip(P, 1e-12, 1.0)
    return -np.mean(np.log(P[np.arange(len(y)), y]))

def temperature_scale(P, y, init_T=1.0):
    z = _safe_logits(P)
    Ts = np.exp(np.linspace(np.log(0.2), np.log(5.0), 50))
    best_T, best_loss = init_T, 1e9
    for T in Ts:
        zT = z / T
        ez = np.exp(zT - zT.max(axis=1, keepdims=True))
        PT = ez / ez.sum(axis=1, keepdims=True)
        L = nll_loss(PT, y)
        if L < best_loss:
            best_loss, best_T = L, T
    return best_T

def expected_calibration_error(P, y, n_bins=15):
    conf = P.max(axis=1); preds = P.argmax(axis=1)
    bins = np.linspace(0.0, 1.0, n_bins+1)
    ece = 0.0
    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        m = (conf > lo) & (conf <= hi)
        if not np.any(m): continue
        acc = np.mean(preds[m] == y[m])
        avg_conf = np.mean(conf[m])
        ece += (np.sum(m) / len(P)) * abs(acc - avg_conf)
    return ece

def brier_score(P, y):
    Y = np.zeros_like(P)
    Y[np.arange(len(y)), y] = 1
    return np.mean((P - Y)**2)

P_cal = _probas_from(df_cal)
y_cal = df_cal['6_way_label'].apply(_to_int_label).values
T = temperature_scale(P_cal, y_cal, init_T=1.0)
print('Best temperature T =', round(T,4))

def apply_temperature(P, T):
    z = _safe_logits(P)
    zT = z / T
    ez = np.exp(zT - zT.max(axis=1, keepdims=True))
    return ez / ez.sum(axis=1, keepdims=True)

P_test_raw_cal = apply_temperature(P_test_raw, T)
ece_before = expected_calibration_error(P_test_raw, df_test['6_way_label'].apply(_to_int_label).values)
ece_after  = expected_calibration_error(P_test_raw_cal, df_test['6_way_label'].apply(_to_int_label).values)
brier_bef  = brier_score(P_test_raw, df_test['6_way_label'].apply(_to_int_label).values)
brier_aft  = brier_score(P_test_raw_cal, df_test['6_way_label'].apply(_to_int_label).values)
print({'ECE_before': round(ece_before,4), 'ECE_after': round(ece_after,4), 'Brier_before': round(brier_bef,4), 'Brier_after': round(brier_aft,4)})

P_wtd_cal = apply_temperature(P_weighted, T)
df_test['y_pred_final'] = P_wtd_cal.argmax(axis=1)
for k in range(NUM_CLASSES):
    df_test[f'y_proba_final_{k}'] = P_wtd_cal[:,k]

acc_final = accuracy_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred_final'])
f1_final  = f1_score(df_test['6_way_label'].apply(_to_int_label), df_test['y_pred_final'], average='macro')
print({'acc_final': round(acc_final,4), 'f1_final': round(f1_final,4)})

"""## 4) Explanation Module (Template‑Guided)"""

import re
def _tokens(s):
    s = str(s).lower()
    return set(re.findall(r"[a-z0-9']+", s))

def jaccard(a, b):
    a, b = set(a), set(b)
    if not a and not b: return 1.0
    return len(a & b) / max(1, len(a | b))

def build_explanation(row):
    text = row.get('clean_title','')
    cap  = row.get('blip_caption','')
    j = jaccard(_tokens(text), _tokens(cap)) if cap else 0.0
    cred = float(row.get('source_cred', 0.5))
    pred_id = int(row.get('y_pred_final', row.get('y_pred_weighted', row.get('y_pred',0))))
    conf = max([float(row.get(f'y_proba_final_{k}', row.get(f'y_proba_weighted_{k}', row.get(f'y_proba_{k}',0.0)))) for k in range(NUM_CLASSES)])
    conflict_score = row.get('conflict_score', None)
    conflict_str = f" conflict≈{float(conflict_score):.2f}" if conflict_score is not None else ''
    if conflict_score is not None and conflict_score >= 0.6 and j < 0.3:
        return (
            f"Text and image appear inconsistent ({'overlap≈'+str(round(j,2))})."+conflict_str+
            f" Using source‑cred≈{cred:.2f}, predicted '{CLASS_NAMES[pred_id]}' with conf≈{conf:.2f}."
        )
    elif j >= 0.5:
        return (
            f"Text and image content align well (overlap≈{j:.2f}). "
            f"With source‑cred≈{cred:.2f}, predicted '{CLASS_NAMES[pred_id]}' with conf≈{conf:.2f}."
        )
    else:
        return (
            f"Alignment unclear (overlap≈{j:.2f}). "
            f"Using source‑cred≈{cred:.2f}, predicted '{CLASS_NAMES[pred_id]}' with conf≈{conf:.2f}."
        )

df_test = df_test.copy()
df_test['explanation'] = df_test.apply(build_explanation, axis=1)
df_test[['clean_title','blip_caption','source','y_pred_final','explanation']].head(3)

"""## 5) Evaluation & Visualization + Saved Artifacts"""

y_true_test = df_test['6_way_label'].apply(_to_int_label).values
y_pred_final = df_test['y_pred_final'].values
acc = accuracy_score(y_true_test, y_pred_final)
f1  = f1_score(y_true_test, y_pred_final, average='macro')
print({'final_accuracy': round(acc,4), 'final_macro_f1': round(f1,4)})

def plot_reliability(P, y, title='Reliability'):
    n_bins = 15
    conf = P.max(axis=1); preds = P.argmax(axis=1)
    bins = np.linspace(0.0, 1.0, n_bins+1)
    mids, accs, confs = [], [], []
    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        m = (conf > lo) & (conf <= hi)
        if not np.any(m): continue
        mids.append((lo+hi)/2); accs.append(np.mean(preds[m]==y[m])); confs.append(np.mean(conf[m]))
    plt.figure(figsize=(5,5))
    plt.plot([0,1],[0,1],'--', linewidth=1)
    plt.plot(confs, accs, marker='o')
    plt.xlabel('Confidence'); plt.ylabel('Accuracy'); plt.title(title); plt.grid(True); plt.show()

plot_reliability(P_test_raw, y_true_test, title='Reliability (Before Calibration)')
plot_reliability(P_wtd_cal, y_true_test, title='Reliability (After Credibility+Calibration)')

cm = confusion_matrix(y_true_test, y_pred_final, labels=list(range(NUM_CLASSES)))
plt.figure(figsize=(6,5)); plt.imshow(cm, interpolation='nearest')
plt.title('Confusion Matrix — Final'); plt.xlabel('Predicted'); plt.ylabel('True')
plt.xticks(range(NUM_CLASSES), CLASS_NAMES, rotation=45, ha='right'); plt.yticks(range(NUM_CLASSES), CLASS_NAMES)
for i in range(NUM_CLASSES):
    for j in range(NUM_CLASSES):
        plt.text(j, i, str(cm[i,j]), ha='center', va='center')
plt.tight_layout(); plt.show()

OUT_DIR = BASE_DIR / 'phase3to5_outputs'
OUT_DIR.mkdir(parents=True, exist_ok=True)
df_test.to_csv(OUT_DIR/'df_results.csv', index=False)
metrics = {
    'acc_raw': float(acc_raw),
    'acc_weighted': float(acc_wtd),
    'f1_raw': float(f1_raw),
    'f1_weighted': float(f1_wtd),
    'ECE_before': float(ece_before),
    'ECE_after': float(ece_after),
    'Brier_before': float(brier_bef),
    'Brier_after': float(brier_aft),
    'acc_final': float(acc_final),
    'f1_final': float(f1_final),
    'best_temperature': float(T)
}
with open(OUT_DIR/'metrics.json','w') as f: json.dump(metrics, f, indent=2)
print('Saved to:', OUT_DIR)